[package]
name = "checkout"
version = "0.1.0"
authors = ["Trevor Wilson <trevor@telco.in>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.24"
secrecy = "0.8.0"

[dev-dependencies]
dotenv = "0.15.0"
rand = "0.8.3"
tokio = { version = "1.17.0", features = ["macros", "rt"] }
once_cell = "1.7.2"
