[package]
name = "checkout"
version = "0.1.0"
authors = ["Trevor Wilson <trevor@telco.in>"]
edition = "2018"

[dependencies]
reqwest = "0.9.24"
serde = "1.0.125"
thiserror = "1.0.24"
futures03 = { package = "futures", version = "0.3.13", features = ["compat"] }
secrecy = "0.7.0"
bigdecimal = "0.1.2"

[dev-dependencies]
dotenv = "0.15.0"
rand = "0.8.3"
tokio = "0.1"
once_cell = "1.7.2"
